Update TileManager.java
Fixes the Null Pointer Error on startup

java.lang.NullPointerException: Cannot invoke "String.split(String)" because "line" is null
        at tile.TileManager.loadMap(TileManager.java:63)
        at tile.TileManager.<init>(TileManager.java:26)
        at main.GamePanel.<init>(GamePanel.java:25)
        at main.PlayRPG.main(PlayRPG.java:14)